echo from 2017-01 to 2017-04
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2017\Backup\2017-03.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2017\Backup\2017-02.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2017\Backup\2017-01.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
echo from 2016-05 to 2016-12
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-12.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-11.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-10.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-09.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-08.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-07.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-06.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2016\2016-05.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
echo 2015-06
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2015\2015-06.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
echo 2014-12 and 2014-06
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2014\2014-12.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
bcp CCDB.dbo.Ravenpack IN "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\RavenPackAnalytics_Companies_1.0_2014\2014-06.tsv" -f "\\evprodfsg01\QR_Workspace\Events\Ravenpack New\Companies\format.fmt" -U tranda -P Ekb4Fpr3s27w79GN -S devExt\ext
